In [2]:
#Program Plan (rough)

#- read_csv file from our file "IST256 Project - Sheet1.csv"
#- create map that shows markers of hometowns of all users, so person inputting can pick where they want to be.
#- start to ask questions to the end user that will narrow down their choice of person
 #   - if statements
  #  -one questions per column in DataFrame
#- Create a new column with "count"
#- all users count starts at 0
#- when there is a matching trait with the user input, add one to the count
#-at the end, the program shouldreturn the users sorted from highest to lowest compatibility
#- end user can choose to look at someones interests in greater detail
#end user can choose to "chat" with someone
    #-ask for recipient and message--> say "message sent"
#eventually we should add titles and nicer font with HTML

In [1]:
import pandas as pd
import folium
import requests
from IPython.display import display, HTML

In [2]:
display(HTML("<h1>Welcome to KINDLING</h1>"))

In [6]:
#This cell can be used to create the map, because we don't have a lot of people, maybe it makes sense to ask "Would you like to choose someone by location or characteristics first"
display(HTML("<h1>Here is a map of our users</h1>"))
CENTER_US = (39.8333333,-98.585522)
usermap = folium.Map(location=CENTER_US, zoom_start=4)
for row in users.to_records():
    pos = (row['Latitude'],row['Longitude'])
    marker = folium.Marker(location=pos, 
                    popup="%s, %s, %s" % (row['First Name'],row['Last Name'],row['Hometown'])
                          )
    usermap.add_child(marker)
usermap

In [4]:
question = input("Would you like to 'send a message' or go to 'matchmaking?' ")

Would you like to 'send a message' or go to 'matchmaking?' send a message

In [5]:
#this is the original dataframe from our file (ALL USERS)
users = pd.read_csv("IST256 Project - Sheet1.csv")
users

,First Name,Last Name,Gender,Hometown,Latitude,Longitude,Preferred Gender,Preferred Eye Color,Preferred Hair Color,Favorite Activity,...,Music,Movie,Kids,Colors,Preferred Tattoos,Preferred Piercings,Hair Color,Eye Color,Tattoos,Piercings
0,Samantha,Carlow,Female,"Saratoga Springs, NY",43.067575,-73.778454,Male,Brown,Brown,Shopping,...,R&B,The Great Gatsby,Yes,Yellow,No,Yes,Brown,Brown,No,Yes
1,Katie,Yerkie,Female,"Hebron, CT",41.652877,-72.391472,Male,Brown,Brown,Cheerleading,...,Country,Caddy Shack,Yes,Blue,No,Yes,Blonde,Green,No,Yes
2,Mark,Leg,Male,"Chicago, IL",41.881832,-87.623177,Female,Brown,Brown,Football,...,Jazz,Dumb and Dumber,No,Black,Yes,No,Red,Brown,Yes,No
3,Bella,Thorne,Female,"Pittsburg, PA",40.440620,-79.995888,Female,Green,Red,Dancing,...,Heavy Metal,The Ring,No,Red,Yes,Yes,Brown,Hazel,Yes,Yes
4,Post,Malone,Male,"Syracuse, NY",43.088947,-76.154480,Female,Brown,Brown,Singing,...,Pop,Anger Management,Yes,Blue,Yes,Yes,Brown,Green,Yes,Yes
5,Rose,Flab,Female,"Jacksonville, FL",30.332180,-81.655647,Female,Hazel,Blonde,Swimming,...,R&B,Tinkerbell,Yes,Pink,No,No,Brown,Brown,No,No
6,Otto,Orange,Male,"Syracuse, NY",43.088947,-76.154480,Female,Blue,Red,Dancing,...,Classical,Beauty and the beast,Yes,Orange,No,No,Blonde,Blue,No,No
7,Samantha,Lee,Female,"New York City, NY",40.730610,-73.935242,Male,Brown,Black,Shopping,...,Pop,Caddy Shack,Yes,Yellow,No,Yes,Blonde,Blue,No,Yes
8,Matt,Sham,Male,"Saratoga Springs, NY",43.067575,-73.778454,Male,Green,Blonde,Baseball,...,Rap,Dirty Dancing,No,Green,No,No,Blonde,Brown,No,No
9,Andrew,Rambunchious,Male,"San Diego,CA",32.715328,-117.157257,Male,Blue,Blonde,Singing,...,Theater,Cats,Yes,Purple,No,Yes,Brown,Brown,No,Yes
10,Dawn,Harper,Female,"Clifton Park, NY",42.845520,-73.818871,Male,Brown,Black,Running,...,R&B,The Ring,No,Yellow,No,No,Brown,Brown,No,No
11,Casey,Harper,Male,"Orlando, FL",28.538340,-81.379242,Female,Green,Brown,Swimming,...,Pop,The Great Gatsby,No,Red,No,Yes,Brown,Hazel,No,Yes
12,Timothy,Run,Male,"Prior Lake, MN",44.713297,-93.422727,Female,Brown,Red,Skating,...,Rap,Doctor Who,Yes,Blue,No,Yes,Red,Blue,No,Yes
13,Jim,Smith,Male,"New York City, NY",40.730610,-73.935242,Female,Brown,Brown,Skiing,...,Pop,Starwars,No,Yellow,No,No,Red,Brown,No,No
14,Jane,Hansen,Female,"Manchester, VT",43.161743,-73.071494,Male,Blue,Blonde,Shopping,...,Indie,Starwars,No,Blue,Yes,Yes,Brown,Brown,Yes,Yes
15,Laurie,Stevens,Female,"Buffalo, NY",42.880230,-78.878738,Male,Brown,Blonde,Skiing,...,Rock and Roll,Avatar,no,Red,Yes,No,Brown,Blue,Yes,No
16,Portritia,Funnel,Female,"Syracuse, NY",43.088947,-76.154480,Male,Green,Brown,Running,...,Country,Anger Management,Yes,Purple,Yes,Yes,Blonde,Brown,Yes,Yes
17,Clemon,Smith,Male,"Westchester, NY",41.116763,-73.799578,Female,Green,Brown,Walks,...,Country,Caddy Shack,No,Pink,Yes,No,Blonde,Blue,Yes,No
18,David,Russo,Male,"Hebron, CT",41.652877,-72.391472,Female,Blue,Blonde,Football,...,Rap,The Ring,Yes,Green,No,No,Brown,Brown,No,No
19,Silvester,Sandler,Male,"Clifton Park, NY",42.845520,-73.818871,Female,Brown,Brown,Sleeping,...,Country,Avengers,No,Black,No,Yes,Blonde,Brown,No,Yes

In [7]:
users['Count'] = 0

In [8]:
#this is the original dataframe from our file (ALL USERS) WITH COUNT INCLUDED
users

,First Name,Last Name,Gender,Hometown,Latitude,Longitude,Preferred Gender,Preferred Eye Color,Preferred Hair Color,Favorite Activity,...,Movie,Kids,Colors,Preferred Tattoos,Preferred Piercings,Hair Color,Eye Color,Tattoos,Piercings,Count
0,Samantha,Carlow,Female,"Saratoga Springs, NY",43.067575,-73.778454,Male,Brown,Brown,Shopping,...,The Great Gatsby,Yes,Yellow,No,Yes,Brown,Brown,No,Yes,0
1,Katie,Yerkie,Female,"Hebron, CT",41.652877,-72.391472,Male,Brown,Brown,Cheerleading,...,Caddy Shack,Yes,Blue,No,Yes,Blonde,Green,No,Yes,0
2,Mark,Leg,Male,"Chicago, IL",41.881832,-87.623177,Female,Brown,Brown,Football,...,Dumb and Dumber,No,Black,Yes,No,Red,Brown,Yes,No,0
3,Bella,Thorne,Female,"Pittsburg, PA",40.440620,-79.995888,Female,Green,Red,Dancing,...,The Ring,No,Red,Yes,Yes,Brown,Hazel,Yes,Yes,0
4,Post,Malone,Male,"Syracuse, NY",43.088947,-76.154480,Female,Brown,Brown,Singing,...,Anger Management,Yes,Blue,Yes,Yes,Brown,Green,Yes,Yes,0
5,Rose,Flab,Female,"Jacksonville, FL",30.332180,-81.655647,Female,Hazel,Blonde,Swimming,...,Tinkerbell,Yes,Pink,No,No,Brown,Brown,No,No,0
6,Otto,Orange,Male,"Syracuse, NY",43.088947,-76.154480,Female,Blue,Red,Dancing,...,Beauty and the beast,Yes,Orange,No,No,Blonde,Blue,No,No,0
7,Samantha,Lee,Female,"New York City, NY",40.730610,-73.935242,Male,Brown,Black,Shopping,...,Caddy Shack,Yes,Yellow,No,Yes,Blonde,Blue,No,Yes,0
8,Matt,Sham,Male,"Saratoga Springs, NY",43.067575,-73.778454,Male,Green,Blonde,Baseball,...,Dirty Dancing,No,Green,No,No,Blonde,Brown,No,No,0
9,Andrew,Rambunchious,Male,"San Diego,CA",32.715328,-117.157257,Male,Blue,Blonde,Singing,...,Cats,Yes,Purple,No,Yes,Brown,Brown,No,Yes,0
10,Dawn,Harper,Female,"Clifton Park, NY",42.845520,-73.818871,Male,Brown,Black,Running,...,The Ring,No,Yellow,No,No,Brown,Brown,No,No,0
11,Casey,Harper,Male,"Orlando, FL",28.538340,-81.379242,Female,Green,Brown,Swimming,...,The Great Gatsby,No,Red,No,Yes,Brown,Hazel,No,Yes,0
12,Timothy,Run,Male,"Prior Lake, MN",44.713297,-93.422727,Female,Brown,Red,Skating,...,Doctor Who,Yes,Blue,No,Yes,Red,Blue,No,Yes,0
13,Jim,Smith,Male,"New York City, NY",40.730610,-73.935242,Female,Brown,Brown,Skiing,...,Starwars,No,Yellow,No,No,Red,Brown,No,No,0
14,Jane,Hansen,Female,"Manchester, VT",43.161743,-73.071494,Male,Blue,Blonde,Shopping,...,Starwars,No,Blue,Yes,Yes,Brown,Brown,Yes,Yes,0
15,Laurie,Stevens,Female,"Buffalo, NY",42.880230,-78.878738,Male,Brown,Blonde,Skiing,...,Avatar,no,Red,Yes,No,Brown,Blue,Yes,No,0
16,Portritia,Funnel,Female,"Syracuse, NY",43.088947,-76.154480,Male,Green,Brown,Running,...,Anger Management,Yes,Purple,Yes,Yes,Blonde,Brown,Yes,Yes,0
17,Clemon,Smith,Male,"Westchester, NY",41.116763,-73.799578,Female,Green,Brown,Walks,...,Caddy Shack,No,Pink,Yes,No,Blonde,Blue,Yes,No,0
18,David,Russo,Male,"Hebron, CT",41.652877,-72.391472,Female,Blue,Blonde,Football,...,The Ring,Yes,Green,No,No,Brown,Brown,No,No,0
19,Silvester,Sandler,Male,"Clifton Park, NY",42.845520,-73.818871,Female,Brown,Brown,Sleeping,...,Avengers,No,Black,No,Yes,Blonde,Brown,No,Yes,0

In [19]:
#these are all variables that will need inputs (when there is a p in front it means preferred)
#I put in answers to get the code running (I think we might have to title all answers)
try:
    user_g = input("What is your gender? (Male or Female) ")
    user_pg = input("Which gender are you attracted to? ")
    user_eye = input("What color are your eyes? ")
    user_peye = input("What color eyes do you prefer in a partner? ")
    user_hair = input("What color is your hair? ")
    user_phair = input("What color hair do you prefer in a partner? ")
    user_tattoos = input("Do you have tattoos? ")
    user_ptattoos = input("Do you like when your partner has tattoos? ")
    user_piercings = input("Do you have any piercings?")
    user_ppiercings = input("Do you like when your partner has piercings? ")
    user_act = input("What is your favorite activity? ")
    user_annoy = input("What is your biggest annoyance? ")
    user_music = input("What type of music do you like? ")
    user_movie = input("What is your favorite movie? ")
    user_kids = input("Do you want to have kids? ")
    user_color = input("What is your favorite color? ")


    users_dict = users.to_dict(orient='records')

    for user in users_dict:
        if user['Preferred Gender'] == user_g and user['Gender'] == user_pg:
            user['Count'] = user['Count'] + 1
            prefgender_df = pd.DataFrame(users_dict)
            prefgender_df = prefgender_df[prefgender_df['Count'] == 1]

    prefgender_dict = prefgender_df.to_dict(orient='records')        
    for user in prefgender_dict:        
        if user['Preferred Eye Color'] == user_eye:
            user['Count'] = user['Count'] + 1
        if user['Eye Color'] == user_peye:
            user['Count'] = user['Count'] + 1
        if user['Preferred Hair Color'] == user_hair:
            user['Count'] = user['Count'] + 1
        if user['Hair Color'] == user_phair:
            user['Count'] = user['Count'] + 1
        if user['Preferred Tattoos'] == user_tattoos:
            user['Count'] = user['Count'] + 1
        if user['Tattoos'] == user_tattoos:
            user['Count'] = user['Count'] + 1
        if user['Preferred Piercings'] == user_piercings:
            user['Count'] = user['Count'] + 1
        if user['Piercings'] == user_ppiercings:
            user['Count'] = user['Count'] + 1
        if user['Favorite Activity'] == user_act:
            user['Count'] = user['Count'] + 1
        if user['Music'] == user_music:
            user['Count'] = user['Count'] + 1
        if user['Annoyances'] == user_annoy:
            user['Count'] = user['Count'] + 1
        if user['Movie'] == user_movie:
            user['Count'] = user['Count'] + 1
        if user['Kids'] == user_kids:
            user['Count'] = user['Count'] + 1
        if user['Colors'] == user_color:
            user['Count'] = user['Count'] + 1
            
except NameError:
    print("Please ensure your typing is correct")

What is your gender? (Male or Female) gfd
Which gender are you attracted to? gfd
What color are your eyes? gfd
What color eyes do you prefer in a partner? gfd
What color is your hair? gfd
What color hair do you prefer in a partner? gfd
Do you have tattoos? fdg
Do you like when your partner has tattoos? f
Do you have any piercings?gdf
Do you like when your partner has piercings? gdf
What is your favorite activity? gfd
What is your biggest annoyance? gfd
What type of music do you like? gfd
What is your favorite movie? gfd
Do you want to have kids? gf
What is your favorite color? gfd

In [20]:
#This is the "prefgender" dataframe that is created in line 26
#Ensures the end user is only getting back people of the same sexuality as themselves
prefgender_df[ ['First Name', 'Last Name', 'Count']]

   First Name Last Name  Count
2        Mark       Leg      1
4        Post    Malone      1
6        Otto    Orange      1
11      Casey    Harper      1
12   Timothy        Run      1
13        Jim     Smith      1
17     Clemon     Smith      1
18      David     Russo      1
19  Silvester   Sandler      1

In [14]:
#the matches dataframe is the prefgender dataframe, but with all of the counts for the characteristics
#I added a compatibility score for this one
matches_df = pd.DataFrame(prefgender_dict)
matches_df['Compatibility'] = matches_df['Count'] / 14
matches_df[ ['First Name', 'Last Name', 'Count', 'Compatibility'] ]

  First Name Last Name  Count  Compatibility
0       Mark       Leg      1       0.071429
1       Post    Malone      1       0.071429
2       Otto    Orange      1       0.071429
3      Casey    Harper      1       0.071429
4   Timothy        Run      1       0.071429
5        Jim     Smith      1       0.071429
6     Clemon     Smith      1       0.071429
7      David     Russo      1       0.071429
8  Silvester   Sandler      1       0.071429

In [15]:
#same as above, but sorted highest to lowest compatibility
print("Here are your matches: ")
matches_df.sort_values('Compatibility', ascending = False)[ ['First Name', 'Last Name', 'Count', 'Compatibility'] ]

Here are your matches:

  First Name Last Name  Count  Compatibility
0       Mark       Leg      1       0.071429
1       Post    Malone      1       0.071429
2       Otto    Orange      1       0.071429
3      Casey    Harper      1       0.071429
4   Timothy        Run      1       0.071429
5        Jim     Smith      1       0.071429
6     Clemon     Smith      1       0.071429
7      David     Russo      1       0.071429
8  Silvester   Sandler      1       0.071429

In [17]:
#starting the see more information about one of their matches
for row in users.to_records():
    seemore = input("Would you like to see more information about one of them? (type 'no' to quit) ")
    if seemore == "no":
        break
    if seemore == "yes":
        fname = input("What is their first name? ")
        display(users[ users['First Name'] == fname])
            
    else:
        print("Please type 'yes' or 'no'")

Would you like to see more information about one of them? (type 'no' to quit) yes
What is their first name? David

,First Name,Last Name,Gender,Hometown,Latitude,Longitude,Preferred Gender,Preferred Eye Color,Preferred Hair Color,Favorite Activity,...,Movie,Kids,Colors,Preferred Tattoos,Preferred Piercings,Hair Color,Eye Color,Tattoos,Piercings,Count
18,David,Russo,Male,"Hebron, CT",41.652877,-72.391472,Female,Blue,Blonde,Football,...,The Ring,Yes,Green,No,No,Brown,Brown,No,No,0

Would you like to see more information about one of them? (type 'no' to quit) no

In [124]:
#We can do the message codes here

name = input("Who would you like to send a message to? (First Name) ")
message = input("Type your message here: ")
for row in users.to_records():
    if name == row['First Name']:
        print(f"Your message {message} to {name} has sent!")

Who would you like to send a message to? (First Name) David
Type your message here: Hi
Your message Hi to David has sent!